# Generated by Django 3.1.5 on 2021-02-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricCarList',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('subname', models.CharField(max_length=30, null=True)),
                ('chargetype', models.CharField(max_length=30, null=True)),
                ('onedistance', models.IntegerField(null=True)),
                ('battery', models.IntegerField(null=True)),
                ('fastcharge', models.CharField(max_length=30, null=True)),
                ('slowcharge', models.CharField(max_length=30, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
